version: "3"

services:
  django:
    image: django4:latest
    tty: true
    stdin_open: true
    volumes:
      - ./django-data:/app/mysite
    ports:
      - 8000:8000
  db:
    image: mariadb:10.10.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpass
      - MYSQL_DATABASE=django
      - MYSQL_USER=django
      - MYSQL_PASSWORD=sqlpass
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
